IBI.System/IBI.MVC/Controllers/SignDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using IBI.Web.ViewModels.Admin.Destinations;
using MvcContrib.Pagination;
using IBI.Shared.Models.Signs;
using System.Xml.Linq;
using System.Xml;
using System.Collections;

using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using IBI.Web.Infrastructure;
using IBI.Shared.Models.Destinations;
using System.IO;
using IBI.Web.Common;
using System.Drawing;
using System.Drawing.Imaging;
using System.Text;
using IBI.Web.Infrastructure.CustomAttributes;
using IBI.Web.Infrastructure.CustomActionResults;
using IBI.Shared;

namespace IBI.Web.Controllers
{
    [AuthorizeLogin]
    public class SignDataController : Controller
    {
        public ActionResult DestinationImages(int signId)
        {
            List<SignXmlLayout> signXmlLayouts = ServiceManager.GetSignImages(signId);

            Sign sign = ServiceManager.GetSignItem(signId);

            var model = new SignDataModel();
            model.MainText = sign.MainText;
            model.SubText = sign.SubText;
            model.Line = sign.Line;
            model.CustomerId = sign.CustomerId;
            model.SignXmlLayout = signXmlLayouts;
            Session["signLayoutImagesData"] = signXmlLayouts;

            /*

            Hashtable signLayoutImagesData = new Hashtable();

            if (signXmlLayouts != null)
            {
                if (signXmlLayouts.Count > 0)
                {
                    foreach (SignXmlLayout signXmlLayout in signXmlLayouts)
                    {
                        string signLayout = signXmlLayout.Type + "-  " + signXmlLayout.Width + "× " + signXmlLayout.Height + "  " + signXmlLayout.Manufacturer + "  -  " + signXmlLayout.Technology ;
                        signLayout += "$" + signId + "," + signXmlLayout.LayoutId + "," + signXmlLayout.GraphicRuleId + "," + signXmlLayout.CustomerId;
                        //string signLayout = signId + "," + signXmlLayout.LayoutId + "," + signXmlLayout.GraphicRuleId + "," + signXmlLayout.CustomerId;
                        List<string> base64Images;

                        if (signLayoutImagesData.ContainsKey(signLayout))
                            base64Images = (List<string>)signLayoutImagesData[signLayout];
                        else
                            base64Images = new List<string>();

                        base64Images = base64Images.Union(Getbase64Images(signXmlLayout.Signs)).ToList();
                        signLayoutImagesData[signLayout] = base64Images;
                    }
                    Session["signLayoutImagesData"] = signLayoutImagesData;
                    model.Base64Images = signLayoutImagesData;
                }
            }
             * */
            return View(model);
        }

        public ActionResult ManualSignEditor()
        {
            return View();
        }
        
        public ActionResult SignEditor()
        {
            return View();
        }
                
        [HttpPost]
        public ActionResult UploadSign(IEnumerable<HttpPostedFileBase> files, FormCollection formCollection)
        {
            foreach (HttpPostedFileWrapper file in files)
            {
                Stream stream = file.InputStream;

                int imageposition = int.Parse(formCollection["imageposition"].ToString());
                int layoutHeight = int.Parse(formCollection["layoutHeight"].ToString());
                int layoutWidth = int.Parse(formCollection["layoutWidth"].ToString());

                ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];

                string grayScalePNGFormat = IsBinaryImageAndPNGFormat(stream, layoutHeight, layoutWidth);

                if (string.IsNullOrEmpty(grayScalePNGFormat))
                {
                    string base64Image = WebUtil.CreateBase64Image(stream);
                    string SignImage = Convert.ToBase64String(AppUtility.ConvertBase64toLEDImage(base64Image)); // WebUtil.ConvertBase64toPicture(base64Image);
                    string base64ImageLarge = Convert.ToBase64String(AppUtility.ConvertBase64toLEDImageLarge(base64Image));                   
                    
                    model.Signs[imageposition].base64ViewString = SignImage;
                    model.Signs[imageposition].Base64String = base64Image;
                    model.Signs[imageposition].base64ViewLargeString = base64ImageLarge;
                    model.Signs[imageposition].SignImage = SignImage;


                    Session["ManualSignDataModel"] = model;
                    return Json(new { PostResult = true, SignImage = SignImage });
                }
                else
                {
                    return Json(new ManualSignDataModel { PostResult = false, ErrorMessage = grayScalePNGFormat });
                }
            }
            return Json(new ManualSignDataModel { PostResult = false, ErrorMessage = "Unknown error" });
        }

        [HttpPost]
        public ActionResult AddSign(int layoutWidth, int layoutHeight)
        {
            ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];
            Stream stream = WebUtil.createBlankImage(layoutWidth, layoutHeight);
            string base64Image = WebUtil.CreateBase64Image(stream);

            //string SignImage = WebUtil.ConvertBase64toPicture(base64Image);
            //imgItem.SignImage = SignImage;

            SignDataImageItem imgItem = new SignDataImageItem();
            imgItem.Base64String = base64Image;

            Byte[] bytes = AppUtility.ConvertBase64toLEDImage(base64Image);
            string ledbase64 = Convert.ToBase64String(bytes);
            imgItem.base64ViewString = ledbase64;
            imgItem.SignImage = ledbase64;

            bytes = AppUtility.ConvertBase64toLEDImageLarge(base64Image);
            ledbase64 = Convert.ToBase64String(bytes);
            imgItem.base64ViewLargeString = ledbase64;

            imgItem.SignDataId = model.Signs.FirstOrDefault().SignDataId;

            model.Signs.Add(imgItem);
            Session["ManualSignDataModel"] = model;
            return PartialView("PartialManualSignEditor", model);
        }
        
        [HttpPost]
        public ActionResult DeleteSign(string imagposition)
        {
            try
            {
                int signPos = int.Parse(imagposition);
                ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];
                model.Signs.RemoveAt(signPos);
                Session["ManualSignDataModel"] = model;
                return PartialView("PartialManualSignEditor", model);
            }
            catch(Exception ex)
            {
                return PartialView("PartialManualSignEditor", Session["ManualSignDataModel"]);
            }
        }
        
        [HttpPost]
        public ActionResult SwapSign(string swapId)
        {
            int sId = int.Parse(swapId);
            ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];

            //model.Signs.RemoveAt(sId);

            SignDataImageItem imgItemsOne = model.Signs[sId - 1];
            SignDataImageItem imgItemsTwo = model.Signs[sId];

            model.Signs[sId - 1] = imgItemsTwo;
            model.Signs[sId] = imgItemsOne;

            Session["ManualSignDataModel"] = model;
            return PartialView("PartialManualSignEditor", model);

        }

        [HttpPost]
        public ActionResult SaveSign()
        {
            ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];

            XDocument xdoc = new XDocument(
                             new XDeclaration("1.0", "utf-8", "yes"),
                             new XElement("signs"));

            xdoc.Root.Add(new XElement("images", new XAttribute("count", model.Signs.Count()),
                             model.Signs.Select((x, index) => new XElement("image", new XAttribute("page", index + 1), new XAttribute("base64", x.Base64String)))
                            ));



            XDocument xdocLarge = new XDocument(
                 new XDeclaration("1.0", "utf-8", "yes"),
                 new XElement("signs"));

            xdocLarge.Root.Add(new XElement("images", new XAttribute("count", model.Signs.Count()),
                             model.Signs.Select((x, index) => new XElement("image", new XAttribute("page", index + 1), new XAttribute("base64", x.Base64String), new XAttribute("base64View", x.base64ViewString), new XAttribute("base64ViewLarge", x.base64ViewLargeString)))
                            ));


            SignXmlData signData = new SignXmlData();
            signData.SignId = model.SignId.ToString();

            signData.Base64 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + xdoc.ToString(SaveOptions.DisableFormatting);//signXML.ToString();
            signData.Page = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" + xdoc.ToString(SaveOptions.DisableFormatting);//signXML.ToString();

            ServiceManager.SaveSignDataImages(model.LayoutId,signData);
            
            return PartialView("PartialManualSignEditor", model);

        }

        [HttpGet]
        public FileResult Download(string imageposition)
        {
            int imagpos = int.Parse(imageposition);
            ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];
            string base64String = model.Signs[imagpos].Base64String;
            byte[] fileBytes = Convert.FromBase64String(base64String);
            string fileName = "SignData.png";
            return base.File(fileBytes, "image/png", fileName);
        }

        //[HttpGet]
        //public FileResult Download(string imageposition)
        //{
        //    int imagpos = int.Parse(imageposition);
        //    ManualSignDataModel model = (ManualSignDataModel)Session["ManualSignDataModel"];

IBI.System/IBI.MVC/Views/SignData/DestinationImages.cshtml
@model  IBI.Web.ViewModels.Admin.Destinations.SignDataModel


@using Kendo.Mvc.UI
@using MvcContrib.Pagination
@using MvcContrib.Sorting 
@using MvcContrib.UI.Grid
@using IBI.Web.Common
@using System.Collections
@using System.Data
@using IBI.Shared.Models.Signs
@using System.Xml.Linq

@{
    ViewBag.Title = "Mermaid IBI - SignData Status";
    Layout = null;
}
    
    <script src="@Url.Content("~/Scripts/kendo/kendo.web.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")" type="text/javascript"></script> 

    <link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.default.min.css")" rel="stylesheet" type="text/css" /> 

    <link href="@Url.Content("~/Content/template/table-grid.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />


    <script>
        function ShowScreenshotsSignData(layoutId, layout, image) {

            var window = $("#ScreenshotSignDataWindow").data("kendoWindow");
            window.title(false);
            $("#ScreenshotSignDataWindow").parent().css("padding-top", "0px");

            $("#ScreenshotSignDataWindow").css("overflow", "hidden");
            $("#ScreenshotSignDataWindow").css("background-color", "#ddd");
            window.center().open().content("<div style='text-align: left; height: 100px'>Please Wait...</div>");
            window.refresh({
                url: "@Url.Action("SignDataFrame", "SignData")",
                data: {
                    LayoutId:layoutId,
                    LayoutCurrent: layout,
                    Base64Image: image
                }
            });
        }

        function OpenSignImageEditor(signId, layoutId, graphicRuleId) {
            var window = $("#SignImageEditor").data("kendoWindow");
            window.title(false);
            $("#SignImageEditor").parent().css("padding-top", "0px");

            $("#SignImageEditor").css("overflow", "hidden");
            $("#SignImageEditor").css("background-color", "#ddd");
            window.center().open().content("<div style='text-align: left; height: 100px'>Please Wait...</div>");
            window.refresh({
                url: "@Url.Action("SignImageEditor", "SignData")",
                data: {
                    signId : signId, 
                    layoutId : layoutId,
                    graphicRuleId : graphicRuleId
                }
            });
        }

        function RefreshMe(id) {
            window.$("#SignImageEditor").data("kendoWindow").close();
            ShowDestinationImages(id);
        }

    </script>

<style>
    .PixelRow {
        height: 2px;
    }
    .PixelImage {
       display: inline-block;
       padding-right: 2px;
    }
    .Content {
        color:red;
        padding: 10px;
        font-weight: bold;
    }
    .spacer
	{
		padding-top: 6px;
	}

     .OFFCell{
		background-color: black; 
		width: 2px; 
		height: 2px;
		float:left;
	}
</style>


<!--Kendo UI Window -> used for both Buses and Group's detail-->

    @(Html.Kendo().Window()
        .Visible(false)
        .Name("ScreenshotSignDataWindow")
        .Modal(false)            
        .Scrollable(false)            
        .Draggable() 
        .Width(720)
        .Height(250)
    )

    @(Html.Kendo().Window()
        .Visible(false)
        .Name("SignImageEditor")
        .Modal(false)
        .Scrollable(false)
        .Title("Destination Signs")
        .Draggable()
        .Width(1100)
        .Height(690)
    )
    <!-- Searched Results - start -->   
    @{
        <b style ="font-size:12px;">Line :  @Model.Line.Trim() </b> <div class='spacer'></div>
        <b style ="font-size:12px;">Main Text : @(Model.MainText != null ? Model.MainText.Trim() : "")</b> <div class='spacer'></div>
        <b style ="font-size:12px;">Sub Text : @(Model.SubText != null ? Model.SubText.Trim() : "")</b> <div class='spacer'></div><hr size='1' />
        List<SignXmlLayout> signXmlLayouts = Model.SignXmlLayout;
        if (signXmlLayouts != null)
        {
            if (signXmlLayouts.Count > 0)
            {
                foreach (var signXmlLayout in signXmlLayouts)
                {
                    <div class='spacer'></div><b style ="font-size:12px;"><u>@(signXmlLayout.Type + "-  " + signXmlLayout.Width + "× " + signXmlLayout.Height + "  " + signXmlLayout.Manufacturer + "  -  " + signXmlLayout.Technology)</u></b><div class="spacer"></div>
                    SignXmlData[] signXmlDatas = signXmlLayout.Signs;
                    int index = 0;
                    string sbOutput = "";
                    int i = 0;
                    if (signXmlDatas != null && signXmlDatas.Length > 0)
                    {
                        foreach (SignXmlData signXmlData in signXmlDatas)
                        {
                            XDocument xdoc = XDocument.Parse(signXmlData.Base64.ToString());
                            
                            var base64Images = (from x in xdoc.Descendants("image")
                                                    select new
                                                    {
                                                        base64 =  x.Attribute("base64").Value,
                                                        base64View = (x.Attribute("base64View") == null ? Convert.ToBase64String(IBI.Shared.AppUtility.ConvertBase64toLEDImage(x.Attribute("base64").Value)) : x.Attribute("base64View").Value),
                                                        base64ViewLarge = (x.Attribute("base64ViewLarge") == null ? Convert.ToBase64String(IBI.Shared.AppUtility.ConvertBase64toLEDImageLarge(x.Attribute("base64").Value)) : x.Attribute("base64ViewLarge").Value)
                                                    }
                                               ).ToList();
                            foreach (var base64Image in base64Images)
                            {
                                if (index == 0)
                                {
                                    sbOutput += "<div>";
                                }
                                sbOutput += "<div class='PixelImage'><a href='javascript:void(0);' onclick=\"ShowScreenshotsSignData(" + signXmlLayout.LayoutId + ",'" + signXmlLayout.Type + "-  " + signXmlLayout.Width + "× " + signXmlLayout.Height + "  " + signXmlLayout.Manufacturer + "  -  " + signXmlLayout.Technology + "','" + i + "')\"><img src='data:image/png;base64," + base64Image.base64View + "'/></a></div>";
                                index = (index + 1) % 3;
                                if (index == 0)
                                {
                                    sbOutput += "</div>";
                                }
                                i++;
                            }
                            sbOutput += "<div class='spacer'></div> <a href='javascript:void(0);' onclick=\"OpenSignImageEditor(" + signXmlLayout.Signs.FirstOrDefault().ContentId + "," + signXmlLayout.LayoutId + "," + signXmlLayout.GraphicRuleId + ")\" class='GrayButton'>Edit</a>";
                            if (index != 0)
                            {
                                sbOutput += "</div>";
                            }
                            
                        }
                    }
                    else
                    {
                        sbOutput += "<div  class='Content'><b>There are no images available</b></div>";
                        sbOutput += "<div class='spacer'></div><a href='javascript:void(0);' onclick=\"OpenSignImageEditor(" + signXmlLayout.Signs.FirstOrDefault().ContentId + "," + signXmlLayout.LayoutId + "," + signXmlLayout.GraphicRuleId + ")\" class='GrayButton'>Edit</a>";
                    }
                    sbOutput += "<div class='spacer'></div><hr size='1' /><div class='spacer'></div>";
                    @Html.Raw(sbOutput);
                }
            }
            else
            {
                <div class="Content" >There are no images available</div> 
            }
        }
        else
        {
            <div class="Content">There are no images available</div> 
        }
    }
    

IBI.System/IBI.MVC/Views/SignData/ManualSignEditor.cshtml
@model  IBI.Web.ViewModels.Admin.Destinations.ManualSignDataModel
@using Kendo.Mvc.UI

@using MvcContrib.Pagination
@using MvcContrib.Sorting 
@using MvcContrib.UI.Grid
@using IBI.Web.Common
@using System.Collections
@using System.Data
@using IBI.Web.ViewModels.Admin.Destinations
@{
    ViewBag.Title = "Mermaid IBI - ManualSignEditor";
    Layout = null;
}

<div id="OuterView" style="overflow-y: scroll; height: 480px;background-color:#efefef;width:97%;left:13px;position:relative;">
    @{
        @Html.Partial("PartialManualSignEditor", Model)
    }
</div>

IBI.System/IBI.MVC/Views/SignData/PartialImageEditorMode.cshtml
@model  IBI.Web.ViewModels.Admin.Destinations.ImageGeneratorModel
    <div style="position:relative;display:inline-block;right:-10px;width:99%">
	    <div style="display: table-cell;position: relative;vertical-align: bottom;width:18%;left: 7px;">
            <div class="Labels">
		        <label title="Line text font">Template</label>
	        </div>
		    <div class="styled-template">
                @Html.DropDownListFor(m => m.SelectedTemplate, Model.Templates)
		    </div>
	    </div>
        @Html.HiddenFor(m => m.SelectedTemplateName)
        <div id ="PPager" style="display: table-cell;position: relative;vertical-align: middle;width:60%;">
            @Html.Partial("PartialPager", Model.ImagePager)
        </div>
    </div>
    <div id="divImageSettings" style="position:relative;display:inline-block;width:99%">
        @Html.Partial("PartialImageGeneratorSettings", Model)
    </div>

IBI.System/IBI.MVC/Views/SignData/PartialManualSignEditor.cshtml
@model  IBI.Web.ViewModels.Admin.Destinations.ManualSignDataModel
@using IBI.Web.ViewModels.Admin.Destinations
@using IBI.Shared.Models.Signs
@{
    List<SignDataImageItem> Signs = Model.Signs;
}
<div class="spacer"></div>
<div class="spacer"></div>
<div class="spacer"></div>
<div class="spacer"></div>
<div class="spacer"></div>
<div class="spacer"></div>
<div class="spacer"></div>
<div class="spacer"></div>
<table border="0" style="border-collapse:collapse;width:100%;">
    <tr>
        <td style="vertical-align: top">
            <div style="height: 50px;"></div>
            <div style="position:relative;top:0px;text-align: right;">
                @{
                    if (Signs.Count <= 1)
                    {
                        <div style="width:61px;height:62px;"></div>
                    }
                    for(int j = 1 ; j < Signs.Count ; j ++)
                    {
                        <div>
                            <input type="hidden" class="swapId" name="hide" value="@j"/>
							<a href="#" class="btnSwap" style="text-decoration: none">
								<div><img src="../Images/signs/swap.png"></div>
							</a>
						</div>
                        if ( j < Signs.Count - 1)
                        {
                            <div class="ButtonSpacer"></div>
                        }
                    }
                }
			</div>
        </td>
        <td>
            <table border="0" style="border-collapse: collapse;width:100%;text-align:left">
                @{
                    int i = 0;
                    foreach (SignDataImageItem Sign in Signs)   
                    {
                        <tr id="tr_@i">
			                <td style="width: 500px"> 
                               <div class="ImageData" style="display: table-cell;background-color: #efefef;vertical-align: middle;text-align: center;width:450px;height:80px;padding-left: 10px;">
                                    <div class="img" style="display:inline-block;position:relative;vertical-align:middle;background-color:white;width:450px;height:66px;">
                                        @*@Html.Raw(Sign.SignImage)*@
                                        <img style="position:relative;top:13px" src='data:image/png;base64,@(Sign.base64ViewString)'/>
                                    </div>
                                </div>
			                </td>
			                <td>
                                <div style="top:-13px;position:relative;text-align:left;display:inline-block;">
                                    <input type="hidden" class="imageposition" name="hide" value="@i"/>
				                    <div class="button">
					                    <a href="#" style="text-decoration: none" class="btnFileSelect" data-ref="tr_@i"><div class="GryButton">Upload</div></a>
                                        <input type="file" class="coreFileElem" name="files" accept=".png" style="display:none" data-url="@Url.Action("UploadSign", "SignData")">
				                    </div>
				                    <div class="button">
					                    <a href="#" class="btnDownload" style="text-decoration: none"><div class="GryButton">Download</div></a>
				                    </div>
				                    <div class="button">
					                    <a href="#" class="btnDelete" style="text-decoration: none"><div class="GryButton">Delete</div></a>
				                    </div>
                                </div>
			                </td>
		                </tr>
                        i++;
                    }
                }
                <tr>
	                <td colspan="3">
		                <div style="display:inline-block;padding-left:10px;position:relative">
    	                    <a href="#" style="text-decoration: none" class="btnAddSign" data-ref="tr_@i"><div class="GrenButton">Add Page</div></a>
                            <input type="file" class="coreAddSign" name="files" accept=".png" style="display:none" data-url="@Url.Action("AddSign", "SignData")">
		                </div>
	                </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

IBI.System/IBI.MVC/Views/SignData/SignDataFrame.cshtml
@{
    ViewBag.Title = "";
    Layout = null;
}

<head>
<link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />
</head>

<body style="margin:0px">

@*<div class="box" style="height:90%; background-color:lightgrey">*@
<iframe id="frmMain" background-color="#efefef" width="100%" height="100%"  scrolling="no" frameborder="0" marginwidth="0" marginheight="0" style="overflow:hidden; overflow-y: hidden; overflow-x:hidden;" src="@Url.Action("SignDataIndex", "SignData", new {LayoutId = ViewData["LayoutId"], layoutCurrent = ViewData["LayoutCurrent"], base64Image = ViewData["Base64Image"] })" />   
@*</div> *@
</body>

IBI.System/IBI.MVC/Views/SignData/Status.cshtml
@model  IBI.Web.ViewModels.Admin.Destinations.SignDataModel
@using Kendo.Mvc.UI

@using MvcContrib.Pagination
@using MvcContrib.Sorting 
@using MvcContrib.UI.Grid
@using IBI.Web.Common
@using System.Collections
@using System.Data
 

@{
    ViewBag.Title = "Mermaid IBI - SignData Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Head{

    
    <script src="@Url.Content("~/Scripts/kendo/kendo.web.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")" type="text/javascript"></script> 
     

    <link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.default.min.css")" rel="stylesheet" type="text/css" /> 

    <link href="@Url.Content("~/Content/template/table-grid.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />
    <script>

        function ShowScreenshots(layout, image,customerId, mainText,subText,line) {

            var window = $("#ScreenshotWindow").data("kendoWindow");

            $("#ScreenshotWindow").css("overflow", "hidden");
            $("#ScreenshotWindow").css("background-color", "#ddd");



            window.center().open().title("Screenshots").refresh({
                url: "@Url.Action("SignDataFrame", "SignData")",
                data: {
                    LayoutCurrent: layout,
                    Base64Image: image,
                    CustomerId:customerId,
                    MainText: mainText,
                    SubText: subText,
                    Line:line
                }
        });
    }
</script>
}

<!--Kendo UI Window -> used for both Buses and Group's detail-->
    
          @(Html.Kendo().Window()
            .Visible(false)
            .Name("ScreenshotWindow")
            .Modal(true)
            .Scrollable(false)
            .Title("Screenshots")
            .Draggable()
            .Width(465)
            .Height(410)
        )



  

<!-- Searched Results - start -->   
<div style ="background-color :lightgray ">
    @{
        
        <b style ="font-size:12px;">Line : @Model.Line</b> <br />
        <b style ="font-size:12px;">Main Text : @Model.MainText</b> <br />
        <b style ="font-size:12px;">Sub Text : @Model.SubText</b> <br />
        
        Hashtable layoutHashData = Model.Base64Images;
        if( layoutHashData != null)
        {

            foreach (DictionaryEntry dEntery in layoutHashData)
            {
                <b style ="font-size:12px;"><u>@dEntery.Key</u></b> <br /><br />
            
                List<string> base64Images = (List<string>)dEntery.Value;

               int index = 0;
               string sbOutput = "";
                foreach (string image in base64Images)
                {
                    if ( index == 0 )
                    {
                        sbOutput += "<div>";
                    }

                    sbOutput += "<a href='javascript:void(0);' onclick=\"ShowScreenshots('" + dEntery.Key + "','" + image + "','" + Model.CustomerId  + "','" + Model.MainText  + "','" + Model.SubText + "','" + Model.Line + "')\"><img src='data:image/png;base64," + image + "' style='background-color:#cccccc;'/></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";

                    index = (index + 1) % 3;
                    if (index == 2)
                    {
                        sbOutput += "</div><br><br>";
                    }
                }

                if(index != 2)
                {
                    sbOutput += "</div>";
                }

                @Html.Raw(sbOutput);
            }
        }
        
    }
        
     
        </div>