IBI.System/IBI.MVC/Controllers/HotspotController.cs
using IBI.Shared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IBI.Web.Controllers
{
    public class HotspotController : Controller
    {
        //
        // GET: /Hotspot/

        [HttpGet]
        public ActionResult Hotspots()
        {
            var model = HotspotServiceManager.Hotspots();
            
            return View(model);
        }

        [HttpGet]
        public ActionResult HotspotList(string search, bool showDeleted = false)
        {
            search = Server.UrlDecode(search);
            var model = HotspotServiceManager.Hotspots(@name: search);

            if (!showDeleted) {
                model.Data = model.Data.Where(d => d.IsDeleted == false).ToList();
            } 
            return View(model);           
        }



        [HttpGet]
        public ActionResult AccessPoints(int hotspotId = 0, int apgId = 0, int id = 0, string name = "", string mac = "")
        {
            //var model = HotspotServiceManager.AccessPoints(hotspotId, apgId, id, name, mac);
            ViewBag.HotspotId = hotspotId;
            ViewBag.AccessPointGroupId = apgId;
            ViewBag.Id = id;
            ViewBag.Name = name;
            ViewBag.MAC = mac;

            ViewBag.Hotspots =  new SelectList(HotspotServiceManager.Hotspots().Data, "ID", "Name", hotspotId);
            ViewBag.AccessPointGroups = new SelectList(HotspotServiceManager.AccessPointGroups(hotspotId: hotspotId).Data, "ID", "Name", apgId); 

            return View();
        }


        [HttpGet]
        public ActionResult AccessPointList(int hotspotId = 0, int apgId = 0, int id = 0, string name = "", string mac = "", bool showDeleted = false, string searchMode = "and")
        {
            //System.Threading.Thread.Sleep(3000);
            var model = HotspotServiceManager.AccessPoints(hotspotId, apgId, id, name, mac, searchMode);

            if (!showDeleted)
            {
                model.Data = model.Data.Where(d => d.IsDeleted == false).ToList();
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult EditAccessPoint(int accessPointId)
        {

            var response = HotspotServiceManager.AccessPoints(id: accessPointId);

            IBI.Shared.Models.Hotspot.AccessPoint model = new Shared.Models.Hotspot.AccessPoint();
            
            if (response.Data.Count() > 0)
            {

                model = response.Data.FirstOrDefault();
                ViewBag.AccessPointGroups = new SelectList(HotspotServiceManager.AccessPointGroups(hotspotId: model.HotspotId).Data, "ID", "Name", model.AccessPointGroup_ID); 
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult EditAccessPoint(IBI.Shared.Models.Hotspot.AccessPoint model)
        {
            bool result = HotspotServiceManager.SaveAccessPoint(model);

            if (Request.IsAjaxRequest())
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult AccessPointActivity(int accessPointId)
        {
            ViewBag.AccessPointId = accessPointId;

            //var model = HotspotServiceManager.AccessPointDailyActivity(accessPointId, startDate.Value, endDate.Value); 
            // return View(model);

            return View();
        }


        [HttpGet]
        public ActionResult AccessPointActivityList(int accessPointId, int days)
        {
            System.Threading.Thread.Sleep(2000);
            DateTime endDate = DateTime.Now.Date;
            DateTime startDate = endDate.AddDays(-(days-1)).Date;

            var model = HotspotServiceManager.AccessPointDailyActivity(accessPointId, startDate, endDate);

            return View(model);
        }


    #region Helper Functions

        public JsonResult AccessPointGroupsByHotspotId(int hotspotId)
        {
            var data = new SelectList(HotspotServiceManager.AccessPointGroups(@hotspotId: hotspotId).Data, "ID", "Name", hotspotId);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

    #endregion
    
    }


    #region Hotspot Service Manager

    public class HotspotServiceManager{

        public static ServiceResponse<List<IBI.Shared.Models.Hotspot.Hotspot>> Hotspots(int id=0, string name="", bool fetchAccessPoints=false)
        {
            HotspotService.HotspotServiceClient client = new HotspotService.HotspotServiceClient();
            var retValue = client.Hotspots(id, name, fetchAccessPoints);
            client.Close();
            return retValue;
        }

        public static ServiceResponse<List<IBI.Shared.Models.Hotspot.AccessPointGroup>> AccessPointGroups(int hotspotId = 0, int id=0, string name="", bool fetchAccessPoints=false)
        {
            HotspotService.HotspotServiceClient client = new HotspotService.HotspotServiceClient();
            var retValue = client.AccessPointGroups(hotspotId, id, name, fetchAccessPoints);
            client.Close();
            return retValue;
        }

        public static ServiceResponse<List<IBI.Shared.Models.Hotspot.AccessPoint>> AccessPoints(int hotspotId=0, int accessPointGroupId=0, int id=0, string name="", string mac="", string searchMode = "and")
        {
            HotspotService.HotspotServiceClient client = new HotspotService.HotspotServiceClient();
            var retValue = client.AccessPoints(hotspotId, accessPointGroupId, id, name, mac, searchMode);
            client.Close();
            return retValue;
        }

        public static ServiceResponse<List<IBI.Shared.Models.Hotspot.AccessPointDailyActivity>> AccessPointDailyActivity(int accessPointId, DateTime startDate, DateTime endDate)
        {
            HotspotService.HotspotServiceClient client = new HotspotService.HotspotServiceClient();
            var retValue = client.AccessPointDailyActivity(accessPointId, startDate, endDate);
            client.Close();
            return retValue;
        }


        internal static bool SaveAccessPoint(Shared.Models.Hotspot.AccessPoint accessPoint)
        {
            HotspotService.HotspotServiceClient client = new HotspotService.HotspotServiceClient();
            var retValue = client.SaveAccessPoint(accessPoint);
            client.Close();
            return retValue.Data;
        }
    }
        #endregion
}

IBI.System/IBI.MVC/Views/Hotspot/AccessPointActivity.cshtml
@{
    Layout = null;
}


<div style="float:right; text-align:right; margin-right:20px;" class="ibiSearchForm">
    No of days
    <select id="lstDays" style="width: 100px; min-width: 100px">
        <option value="10" selected="selected">10</option>
        <option value="30">30</option>
        <option value="100">100</option>
        <option value="365">365</option>
        <option value="2048">Always</option>
    </select>
    
    <input id="btnFetchOlderActivity" type="button" value="Fetch" class="green" />
</div>

<div>
    <div id="dvActivityList" class="ibiGrid">
        <h2>Loading data ... </h2>
    </div>
</div>

    <script>
        $(document).ready(function () {

            SearchActivity(10);

            $("#btnFetchOlderActivity").on('click', function () {
                SearchActivity($("#lstDays").val());
            });



            function SearchActivity(adays) {
                debugger
                EnableControls_ActivityList(false);
                $("#dvActivityList").html('Loading data');
                var url = '@Url.Action("AccessPointActivityList")' + '?accessPointId=@ViewBag.AccessPointId&days=' + adays;
                $("#dvActivityList").load(url, function () {
                    EnableControls_ActivityList(true);
                });
            }


            function EnableControls_ActivityList(bool) {

                var className = "";
                var cursor = "";
                if (bool) {
                    className = "green";
                    cursor = "pointer";
                }
                else {
                    className = "grey";
                    cursor = "default";
                }

                $('input[type="button"]').prop('disabled', !bool);
                $('input[type="button"]').prop('class', className);
                $('input[type="button"]').css('cursor', cursor);

            }
        });


    </script>

IBI.System/IBI.MVC/Views/Hotspot/AccessPointActivityList.cshtml
@model IBI.Shared.Models.ServiceResponse<List<IBI.Shared.Models.Hotspot.AccessPointDailyActivity>>


@{
    Layout = null;
}


<style>
    #activityTable th:nth-child(1), #tblActivityRow td:nth-child(1) {
        max-width: 80px;
        min-width: 80px;
    }

    #activityTable th:nth-child(2), #tblActivityRow td:nth-child(2) {
        max-width: 80px;
        min-width: 80px;
    }

    #activityTable th:nth-child(3), #tblActivityRow td:nth-child(3) {
        max-width: 80px;
        min-width: 80px;
    }

    #activityTable th:nth-child(4), #tblActivityRow td:nth-child(4) {
        max-width: 110px;
        min-width: 110px;
    }

    #activityTable th:nth-child(5), #tblActivityRow td:nth-child(5) {
        max-width: 100px;
        min-width: 100px;
    }

    #activityTable th:nth-child(6), #tblActivityRow td:nth-child(6) {
        max-width: 90px;
        min-width: 90px;
    }
     
</style>

<div class="heading">@Model.Data.Count() records found</div>
<div style="width:100%; height: 380px; overflow:scroll">
    <table id="activityTable" class="tablesorter">
        <thead id="activityHeader">
            <tr style="display:@(Model.Data.Count()==0 ? "none" : "")">
                <th>Day</th>
                <th>Send (MBs)</th>
                <th>Received (MBs)</th>
                <th>Successful Logins</th>
                <th>Failed Logins</th>
                <th>Activity Time (s)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var a in Model.Data)
            {
                <tr id="tblActivityRow">
                    <td>@a.Date.Value.ToString("yyyy-MM-dd")</td>
                    <td style="text-align:right">@(a.BytesSent / 1024 / 1024)</td>
                    <td style="text-align:right">@(a.BytesReceived / 1024 / 1024)</td>
                    <td style="text-align:right">@a.SuccessfulLogins</td>
                    <td style="text-align:right">@a.FailedLogins</td>
                    <td style="text-align:right">@a.ActivityTime</td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
            </tr>
        </tfoot>
    </table>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        debugger
        $("#activityTable").tablesorter();
        $('#activityHeader').scrollToFixed(); 
    });

</script>

IBI.System/IBI.MVC/Views/Hotspot/AccessPointList.cshtml
@model IBI.Shared.Models.ServiceResponse<List<IBI.Shared.Models.Hotspot.AccessPoint>>

@{
    Layout = null;
}

<style>
    #fixedHeader th:nth-child(1), #tblRow td:nth-child(1) {
        max-width: 40px;
        min-width: 40px;
    }
    #fixedHeader th:nth-child(2), #tblRow td:nth-child(2) {
        max-width: 145px;
        min-width: 145px;
    }
    #fixedHeader th:nth-child(3), #tblRow td:nth-child(3) {
        max-width: 110px;
        min-width: 110px;
    }
    #fixedHeader th:nth-child(4), #tblRow td:nth-child(4) {
        max-width: 130px;
        min-width: 130px;
    }
    #fixedHeader th:nth-child(5), #tblRow td:nth-child(5) {
        max-width: 140px;
        min-width: 140px;
    }
    #fixedHeader th:nth-child(6), #tblRow td:nth-child(6) {
        max-width: 80px;
        min-width: 80px;
    }
    #fixedHeader th:nth-child(7), #tblRow td:nth-child(7) {
        max-width: 135px;
        min-width: 135px;
    }
    #fixedHeader th:nth-child(8), #tblRow td:nth-child(8) {
        max-width: 150px;
        min-width: 150px;
    }
    #fixedHeader th:nth-child(9), #tblRow td:nth-child(9) {
        max-width: 80px;
        min-width: 80px;
    }
    #fixedHeader th:nth-child(10), #tblRow td:nth-child(10) {
        min-width: 50px;
        background-image:none;
    }
     
</style>
<div class="heading">@Model.Data.Count() Access points found</div>
<table id="myTable" class="tablesorter">
    <thead id="fixedHeader">

        <tr style="display:@(Model.Data.Count()==0 ? "none" : "")">
            <th>Id</th>
            <th>Name</th>
            <th>MAC</th>
            <th>Hotspot</th>
            <th>AP-Group</th>
            <th style="text-align: center;">Enabled</th>
            <th>Last Ping</th>
            <th>Today Usage (S/R)</th>
            <th style="text-align: center;">Deleted</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ap in Model.Data)
        {
            <tr id="tblRow">
                <td>@ap.ID</td>
                <td>@ap.Name</td>
                <td>@ap.MAC</td>
                <td>@ap.HotspotName</td>
                <td>@ap.AccessPointGroupName</td>
                <td style="font-weight: bold; text-align:center; color:@(ap.Enabled ? "green" : "red")">@(ap.Enabled ? "Yes" : "No")</td>
                <td>@(ap.LastPing != null ? ap.LastPing.ToString("yyyy-MM-dd HH:mm:ss") : "")</td>
                <td style="text-align:right">@(ap.TodayUsage == null ? "0/0" : (ap.TodayUsage.BytesSent / 1024 / 1024) + " MB / " + (ap.TodayUsage.BytesReceived / 1024 / 1024) + " MB")</td>
                <td style="font-weight: bold; text-align:center; color:@(ap.IsDeleted? "red" : "green")">@(ap.IsDeleted ? "Yes" : "No")</td>
                <td style="text-align:center">
                    <a id="lnkEditAccessPoint" onclick="OpenWindow_EditAccessPoint(@ap.ID)" href="javascript:void(0)" title="Edit" data-id="@ap.ID"><img src="~/Images/destinations/edit.png" /></a>
                    &nbsp;&nbsp;&nbsp;
                    <a id="lnkShowAccessPointActivity" onclick="OpenWindow_ShowAccessPointActivity(@ap.ID)" href="javascript:void(0)" title="Daily activity" data-id="@ap.ID"><img src="~/Images/destinations/activity.png" /></a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>

    </tfoot>
</table>

<script type="text/javascript">
     $(document).ready(function () { 
        $("#myTable").tablesorter();
        $('#fixedHeader').scrollToFixed();
     });
     
</script>

IBI.System/IBI.MVC/Views/Hotspot/AccessPoints.cshtml
@using Kendo.Mvc.UI
@{
    ViewBag.Title = "IBI: Hotspot - Access Points";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Head{
     
    <link href="@Url.Content("~/Content/dynatree/skin/ui.dynatree.destinations.css")" rel="stylesheet" type="text/css" />
        
    <script src="@Url.Content("~/Scripts/kendo/kendo.web.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")" type="text/javascript"></script>
    
    <link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/kendo.default.min.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/Content/template/ibi-controls.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/angular/libraries/scrollFix/jquery-scrolltofixed-min.js")"></script>
     
    <script src="@Url.Content("~/Scripts/jquery/jquery.tablesorter.min.js")"></script>
    
    @if (this.Context == null)
    {
        <script src="../Scripts/kendo/kendo.all-vsdoc.js" type="text/javascript"></script>
        <script src="../Scripts/jquery/json2.js" type="text/javascript"></script>
    }


}
<form id="frmSearch" method="post">

    <div class="ibiSearchForm">
        <table>
            <tr>
                <td colspan="5">
                    <h2>Access Points</h2>
                </td>
            </tr>
            <tr>
                <th style="width:150px;">Hotspot</th>
                <td>
                    @Html.DropDownList("SelectedHotspot", (IEnumerable<SelectListItem>)ViewBag.Hotspots, "- All -", new { @onchange = "Hotspot_Changed()" })
                </td>
                <th>
                   Include deleted
                </th>
                <td>
                    <div style="display:inline; vertical-align:top"> YES &nbsp; <input type="radio" id="rdoStatus1" name="rdoStatus" value="true"  style="margin-top:3px;"/></div>
                    <div style="display:inline; vertical-align:top"> NO &nbsp; <input type="radio" id="rdoStatus2" name="rdoStatus" value="false" checked="checked" /></div>
                </td>
                <td></td>
            </tr>
            <tr>
                <th>Access Point Group</th>
                <td>
                    @Html.DropDownList("SelectedAccessPointGroup", (IEnumerable<SelectListItem>)ViewBag.AccessPointGroups, "- All -", new {@onchange = "AccessPointGroup_Changed()" })
                    @*@Html.DropDownList("SelectedAccessPointGroup", (IEnumerable<SelectListItem>)ViewBag.AccessPointGroups, "- All -", new { @onchange = "SearchAccessPoints()" })*@
                </td>
                <th>
                    Search mode
                </th>
                <td>
                    <div style = "display:inline; vertical-align:top"> AND &nbsp; <input type="radio" id="rdoSearchMode1" name="rdoSearchMode" value="and" checked="checked" onclick="rdoSearchMode_Click()" /> </div> 
                    <div style = "display: inline; vertical-align: top; "> OR &nbsp; <input type="radio" id="rdoSearchMode2" name="rdoSearchMode" value="or" onclick="rdoSearchMode_Click()" /></div> 
                </td>
                <td></td>
            </tr>

            <tr>
                <th>Access Point</th>
                <td style="max-width: 540px; min-width: 540px;">
                    <input type="text" id="id" placeholder="Id" />
                    &nbsp;&nbsp; <label id="lblOperator1">AND</label> &nbsp;&nbsp;
                    <input type="text" id="name" placeholder="Name" />
                    &nbsp;&nbsp; <label id="lblOperator2">AND</label> &nbsp;&nbsp;
                    @*<div style="display: inline-block; vertical-align: middle">
                        <label for="chkStatus">Show Deleted</label>
                        <input type="checkbox" id="chkStatus" style="vertical-align:middle" />
                    </div>*@
                </td>
                <td colspan="2" style="padding-left:0px;">
                    <input type="text" id="mac" placeholder="MAC" />
                </td>
                <td style="min-width:200px; text-align:right">
                    <input type="submit" id="btnSearch" value="Search" />
                </td>
            </tr>
        </table>
    </div>

</form>

<br /><br />


<div id="apList" class="ibiGrid" style="display:block">
    <h2>Loading Access Points ... </h2>
</div>


@(Html.Kendo().Window()
                .Visible(false)
                .Name("EditAccessPoint")
                .Modal(true)
                .Scrollable(false)
                .Title("Edit Access Point")
                .Draggable()
                .Width(450)
                .Height(280)
                .Events(events => events.Close("ReloadParent"))
)

@(Html.Kendo().Window()
                .Visible(false)
                .Name("AccessPointActivity")
                .Modal(true)
                .Scrollable(false)
                    .Title("Access Point Activity")
                .Draggable()
                .Width(700)
                .Height(400)
                //.Events(events => events.Close("ReloadParent"))
)


<script>

    $(document).ready(function () {
         
        @*
        var url = '@Url.Action("AccessPointList")' + '?hotspotId=@(ViewBag.HotspotId)&apgId=@(ViewBag.AccessPointGroupId)&id=@(ViewBag.Id)&name=@(ViewBag.Name)&mac=@(ViewBag.MAC)&showDeleted=false'
        $("#apList").load(url);
        *@
        SearchAccessPoints();
        //end page - load


        $("#frmSearch").on('submit', function () {
            SearchAccessPoints();
            return false;
        })//end frmSearch - submit


        $("#btnSearch").on('click', function () {

            SearchAccessPoints();
            return false;
        })//end btnSearch - click

        $("#lnkEditAccessPoint").on('click', 'a', function () {

        });//end lnkEditAccessPoint - click

        $("#lnkShowAccessPointActivity").on('click', function () {

        });//end lnkShowAccessPointActivity - click

    });


    function rdoSearchMode_Click() {
        var value = $("input:radio[name ='rdoSearchMode']:checked").val();
        //alert(value);
        $("#lblOperator1").html(value.toUpperCase());
        $("#lblOperator2").html(value.toUpperCase());
    }

    function Hotspot_Changed(){

        var hotspotId = $('#SelectedHotspot').val();

        if (hotspotId == '')
            hotspotId = 0;

        var id = $("#id").val('');
        var name = $("#name").val('');
        var mac = $("#mac").val('');

        $.ajax({
            url: '../Hotspot/AccessPointGroupsByHotspotId',
            type: "GET",
            dataType: "JSON",
            data: { HotspotId: hotspotId },
            success: function (apGroups) {
                $("#SelectedAccessPointGroup").html(""); // clear before appending new list
                $("#SelectedAccessPointGroup").append(
                        $('<option></option>').val(0).html('- All -'));

                $.each(apGroups, function (i, apGroup) {
                    $("#SelectedAccessPointGroup").append(
                        $('<option></option>').val(apGroup.Value).html(apGroup.Text));
                });

                if (hotspotId == 0) {
                    $("#SelectedAccessPointGroup").prop('disabled', 'disabled');
                }
                else {
                    $("#SelectedAccessPointGroup").prop('disabled', false);
                }
               // SearchAccessPoints();
            }
        });

    }

    function AccessPointGroup_Changed() {
        var id = $("#id").val('');
        var name = $("#name").val('');
        var mac = $("#mac").val('');
    }

    function SearchAccessPoints() {
        $("#apList").html('<h2>Loading Access Points... </h2>');
        debugger
        var hotspotId = $("#SelectedHotspot").val();
        var apgId = $("#SelectedAccessPointGroup").val();
        var id = $("#id").val();
        var name = $("#name").val();
        var mac = $("#mac").val();
        //var showDeleted = $("#chkStatus").is(':checked');
        var showDeleted = $("input:radio[name ='rdoStatus']:checked").val();
        var searchMode = $("input:radio[name ='rdoSearchMode']:checked").val();

        //alert(showDeleted);
        //alert(searchMode);

        if (hotspotId == '')
            hotspotId = 0;
        if (apgId == '')
            apgId = 0;

        if (hotspotId == 0) {
            $("#SelectedAccessPointGroup").prop('disabled', 'disabled');
        }
        else {
            $("#SelectedAccessPointGroup").prop('disabled', false);
        }

        EnableControls(false);
        var url = '@Url.Action("AccessPointList")' + '?hotspotId=' + hotspotId + '&apgId=' + apgId + '&id=' + id + '&name=' + encodeURIComponent(name) + '&mac=' + encodeURIComponent(mac) + '&showDeleted=' + showDeleted + '&searchMode=' + searchMode;
        //alert(url);
        $("#apList").load(url, function () {
            EnableControls(true);
        });
    }


    function OpenWindow_EditAccessPoint(apId) {
        //alert(id);
        var window = $("#EditAccessPoint").data("kendoWindow");

        $("#EditAccessPoint").css("overflow", "hidden");
        $("#EditAccessPoint").css("background-color", "#fff");

        window.center().open().content("<div style='text-align: left; height: 100px;'>Please Wait...</div>").title("Edit Access Point");
        window.refresh({
            url: '@Url.Action("EditAccessPoint", "Hotspot")',
            data: {
                accessPointId: apId
            }
        });
    }

    function OpenWindow_ShowAccessPointActivity(apId) {
        //alert(id);
        var window = $("#AccessPointActivity").data("kendoWindow");

        $("#AccessPointActivity").css("overflow", "hidden");
        $("#AccessPointActivity").css("background-color", "#fff");

        window.center().open().content("<div style='text-align: left; height: 100px'>Please Wait...</div>").title("Access Point Activity");
        window.refresh({
            url: '@Url.Action("AccessPointActivity", "Hotspot")',
            data: {
                accessPointId: apId
            }
        });
    }


    function EnableControls(bool) {

        var className = "";
        var cursor = "";
        if (bool) {
            className = "green";
            cursor = "pointer";
        }
        else {
            className = "grey";
            cursor = "default";
        }

        $('input[type="submit"]').prop('disabled', !bool);
        $('input[type="submit"]').prop('class', className);
        $('input[type="submit"]').css('cursor', cursor);

    }

    function ReloadParent() {
        //alert('realoading');
        SearchAccessPoints();
    }

</script>

IBI.System/IBI.MVC/Views/Hotspot/HotspotList.cshtml
@model IBI.Shared.Models.ServiceResponse<List<IBI.Shared.Models.Hotspot.Hotspot>>

@{
    Layout = null;
}

<table>
    <thead>
        <tr>
            <td colspan="10"> 
                <div class="heading">@Model.Data.Count() hotspots found</div>
            </td>
        </tr>
        <tr style="display:@(Model.Data.Count()==0 ? "none" : "")">
            <th>Name</th>
            <th>APs</th>
            <th>Hotspot Id</th>
            <th>SSID</th>
            <th>Landing Page</th>
            <th>Theme</th>
            <th>Start Page</th>
            <th>Registrtion required</th>
            <th>Daily user limit (MB)</th>
            <th style="text-align:center">Deleted</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var hotspot in Model.Data)
        {
            <tr>
                <td><h3>@Html.ActionLink(hotspot.Name, "AccessPoints", "Hotspot", new { hotspotId = hotspot.ID }, new { })</h3></td>
                <td></td>
                <td>@hotspot.HotspotID</td>
                <td>@hotspot.SSID</td>
                <td>@hotspot.LandingPage</td>
                <td>@hotspot.Theme</td>
                <td>@hotspot.StartPage</td>
                <td>@(hotspot.RegistrationRequired ? "Yes" : "No")</td>
                <td style="text-align:right">@hotspot.DailyUserUsageLimitMB</td>
                <td style="font-weight: bold; text-align:center; color:@(hotspot.IsDeleted ? "red" : "green")">@(hotspot.IsDeleted ? "Yes" : "No")</td>
            </tr>
            foreach (var apg in hotspot.AccessPointGroups)
            {
                <tr>
                    <td> &nbsp;&nbsp;&nbsp;&nbsp; @Html.ActionLink(@apg.Name, "AccessPoints", "Hotspot", new { hotspotId = hotspot.ID, apgId = apg.ID }, new { })</td>
                    <td style="text-align:right">@apg.TotalAccessPoints</td>
                    <td></td>
                    <td>@apg.SSID</td>
                    <td>@apg.LandingPage</td>
                    <td>@apg.Theme</td>
                    <td>@apg.StartPage</td>
                    <td></td>
                    <td></td>
                    <td style="font-weight: bold; text-align:center; color:@(apg.IsDeleted ? "red" : "green")">@(apg.IsDeleted ? "Yes" : "No")</td>
                </tr>
            }

        }
    </tbody> 
</table>