IBI.System/IBI.MVC/ViewModels/BusTree/Screenshots/ListContainerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MvcContrib.Pagination;
using MvcContrib.Filters;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;


namespace IBI.Web.ViewModels.BusTree.Screenshots

{

    public class ListContainerViewModel
    {
        public IPagination<IBI.Web.ViewModels.BusTree.Screenshots.Screenshot> PagedList { get; set; } 
        public GridSortOptions GridSortOptions { get; set; }
    }
}

IBI.System/IBI.MVC/ViewModels/BusTree/Screenshots/ScreenshotViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;

namespace IBI.Web.ViewModels.BusTree.Screenshots
{
    public class Screenshot
    {
        [DataMember]
        public string BusNumber { get; set; }
        [DataMember]
        public string ClientType { get; set; }
        [DataMember]
        public string ImageIndex { get; set; }
        [DataMember]
        public string ImagePath { get; set; }
        [DataMember]
        public string ImageDate { get; set; }

        
    }
}

IBI.System/IBI.MVC/Controllers/ScreenshotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Web.Mvc;
using MvcContrib.UI.Grid;
using IBI.Web.ViewModels.BusTree.Screenshots;
using System.Data;
using MvcContrib.Pagination;
using MvcContrib.Sorting;
using MvcContrib.UI.Grid;
using IBI.Web.Infrastructure.CustomAttributes;
using IBI.Web.Common;

namespace IBI.Web.Controllers
{ 
    [AuthorizeLogin]
    public class ScreenshotController : Controller
    {
        //
        // GET: /Screenshot/

        //public ActionResult Index(string busNumber)
        //{
        //    //ViewData["BusNumber"] = busNumber;
        //    return View();
        //}
         
        [HttpGet]
        public ActionResult Frame(string busNumber, string clientType)
        {
            ViewData["BusNumber"] = busNumber;
            ViewData["ClientType"] = clientType;
            return View();
        }
         
        public ActionResult Index(
            string busNumber,
            GridSortOptions gridSortOptions,
            int? page,
            string clientType = "DCU")
        {

            if (busNumber == "" && ViewData["BusNumber"] != null)
                busNumber = ViewData["BusNumber"].ToString();
            
            if (clientType == "" && ViewData["ClientType"] != null)            
                clientType = ViewData["ClientType"].ToString();

            ViewData["BusNumber"] = busNumber;
            ViewData["ClientType"] = clientType;

            var list = GetImages(busNumber, clientType);

            // Set default sort column
            if (string.IsNullOrWhiteSpace(gridSortOptions.Column))
            {
                gridSortOptions.Column = "ImagePath";
                gridSortOptions.Direction = SortDirection.Ascending;
            }


            int defaultPage = list.Count() > 0 ? list.Count : 1;
            // Order and page the product list
            var pagedList = list
                .OrderBy(gridSortOptions.Column, gridSortOptions.Direction)
                .AsPagination(page ?? defaultPage, 1);


            var listContainer = new ListContainerViewModel
            {
                PagedList = pagedList,
                GridSortOptions = gridSortOptions
            };

            return View(listContainer);
        }  

       
        #region private helper functions

        private List<Screenshot> GetImages( string busNumber, string clientType, string wantedImage="")
        {
            List<Screenshot> screenshotList = new List<Screenshot>();

            String folderName = "../Resources/Screenshots/" + clientType + "/" + busNumber + "/";

            //this.CllImageName.InnerText = Server.MapPath(folderName);
            string imageIndex = "0";

            if (Directory.Exists(Server.MapPath(folderName)))
            {
                String[] imageList = Directory.GetFiles(Server.MapPath(folderName), "*.jpg");
                
                for (int i = 0; i < imageList.Length; i++)
                {
                    String imagePath = imageList[i];

                    imageIndex = i.ToString();

                    //extract time from image
                   
                        string date2Compare = Path.GetFileNameWithoutExtension(imagePath).Substring(Path.GetFileNameWithoutExtension(imagePath).Length - 15);

                        int year = int.Parse(date2Compare.Substring(0, 4));
                        int month = int.Parse(date2Compare.Substring(4, 2));
                        int day = int.Parse(date2Compare.Substring(6, 2));
                        int hour = int.Parse(date2Compare.Substring(9, 2));
                        int minute = int.Parse(date2Compare.Substring(11, 2));
                        int second = int.Parse(date2Compare.Substring(13, 2));

                       // DateTime newDate = new DateTime(year, month, day, hour, minute, second);

                        
                     DateTime imgDt = new DateTime(year, month, day, hour, minute, second);

                    Screenshot sshot = new Screenshot();
                    sshot.BusNumber = busNumber;
                    sshot.ClientType = clientType;
                    sshot.ImageIndex = imageIndex;
                    sshot.ImagePath = folderName + Path.GetFileName(imagePath);
                    sshot.ImageDate = imgDt.ToString(Settings.DateTimeFormat);       

                    screenshotList.Add(sshot); 

                }
            }

            return screenshotList.OrderByDescending(x => x.ImagePath).ToList(); 
        } 
         
        
        #endregion
    }
}

IBI.System/IBI.MVC/Views/Screenshot/Frame.cshtml
@{
    ViewBag.Title = "";
    Layout = null;
}

<head>
<link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />
</head>

<body style="margin:0px">

<div style="height:100%">
<iframe id="frmMain" width="100%" height="100%"  scrolling="no" frameborder="0" marginwidth="0" marginheight="0" style="overflow:hidden; overflow-y: hidden; overflow-x:hidden;" src="@Url.Action("Index", "Screenshot", new { busNumber = ViewData["BusNumber"], clientType = ViewData["ClientType"] })" />   
</div> 
</body>

IBI.System/IBI.MVC/Views/Screenshot/Index.cshtml
@model IBI.Web.ViewModels.BusTree.Screenshots.ListContainerViewModel

@{
    Layout = null;
 }

@using MvcContrib.Pagination
@using MvcContrib.Sorting 
@using MvcContrib.UI.Grid
@using IBI.Web.Common

 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js" type="text/javascript"></script>
    
<script src="@Url.Content("~/Scripts/jquery/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script> 
<link href="@Url.Content("~/Content/template/popup.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/template/table-grid.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" /> 

<script src="@Url.Content("~/Scripts/kendo/kendo.web.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/kendo/kendo.aspnetmvc.min.js")" type="text/javascript"></script> 
     

<link href="@Url.Content("~/Content/kendo/kendo.common.min.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/kendo/kendo.default.min.css")" rel="stylesheet" type="text/css" /> 

<link href="@Url.Content("~/Content/template/table-grid.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/template/general.css")" rel="stylesheet" type="text/css" />

<script>
    function CloseWindow() {
        window.parent.$("#ScreenshotWindow").data("kendoWindow").close();
    }
</script>

<style>
    .InActiveUnit
    {
        text-decoration: none;
        color: #aaaaaa;                
        font-size: 15px;
        font-weight: bold;
    }
        
    .ActiveUnit
    {
        text-decoration: none;
        color: #94B52C;                
        font-weight: bold;
        font-size: 15px;
    }
</style>

<table style="margin-left:6px;padding-left: 6px;padding-top: 2px;left: 6px;position: relative; width:95%">
    <tr>
        @{
            string dcuCss = ViewData["ClientType"].ToString() == "DCU" ? "ActiveUnit" : "InactiveUnit";
            string vtcCss = ViewData["ClientType"].ToString() == "VTC" ? "ActiveUnit" : "InactiveUnit";
            string ccuCss = ViewData["ClientType"].ToString() == "CCU" ? "ActiveUnit" : "InactiveUnit";  
         } 
        <td>
            @Html.ActionLink("CCU", "Index", new { busNumber = @ViewData["BusNumber"], clientType = "CCU" }, new { @class = ccuCss })
            &nbsp;&nbsp;&nbsp;
            @Html.ActionLink("DCU", "Index", new { busNumber = @ViewData["BusNumber"], clientType = "DCU" }, new { @class = dcuCss })
            &nbsp;&nbsp;&nbsp;
            @Html.ActionLink("VTC", "Index", new { busNumber = @ViewData["BusNumber"], clientType = "VTC" }, new { @class = vtcCss })

        </td>
        <td style="text-align: right;">
            <img src="~/Images/infotainment/close.png" onclick="CloseWindow()"/>
        </td>
    </tr>
    <tr>
        <td colspan="2">
             @{
               var grid = Html.Grid(Model.PagedList)
               .Columns(column =>
               {
                   column.Custom(c => (WebUtil.FormatScreenshot(string.Format("{0}|{1}|{2}|{3}|{4}", c.BusNumber, c.ClientType, c.ImageIndex, c.ImagePath, c.ImageDate))));

               })
             .Attributes(@class => "table-list")
             .RenderUsing(new IBI.Web.Infrastructure.ContribGrid.GridNoHeaderRenderer<IBI.Web.ViewModels.BusTree.Screenshots.Screenshot>())
             .RowAttributes(data => new MvcContrib.Hash(@class => data.IsAlternate == true ? "gridrow" : "gridrow"))  
             ;
           }
             @{
                 if (Model.PagedList.Count() > 0)
                 { 
                    @grid 
                 
                     Html.RenderPartial("Pager", Model.PagedList);
                 }
                 else
                 {
                     <div class="no-data" style="border-radius: 3px;width: 400px;height: 50px;">There are no images available</div> 
                 }
              }
        </td>
    </tr>
</table>
  