IBI.System/IBI.MVC/ViewModels/Admin/Configurations/ConfigurationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IBI.Web.ViewModels.Admin.Configurations
{
    public class ConfigurationModel
    {
        [HiddenInput(DisplayValue = false)]
        public string ConfgurationChanged1 { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string ConfgurationChanged2 { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string ConfgurationChanged3 { get; set; }

        public int ConfgurationPropertyId1 { get; set; }
        public int ConfgurationPropertyId2 { get; set; }
        public int ConfgurationPropertyId3 { get; set; }

        public SelectList ConfigurationPropertiesList { get; set; }

        public string ConfigSelectionStatus { get; set; }

        //Constructor
        public ConfigurationModel() 
        {
            this.ConfigurationPropertiesList = GetConfigurationProperties();
            ConfigSelectionStatus = this.ConfigurationPropertiesList.Count() > 1 ? "1" : "0";
        }

        public static SelectList GetConfigurationProperties()
        {
            List<IBI.Shared.Models.Configuration> confgs = Common.CurrentUser.ConfigurationList;
           
            return new SelectList(confgs,
                            "ConfgurationPropertyId",
                            "PropertyName"
                            );
        }
        
    }
}

IBI.System/IBI.MVC/ViewModels/Admin/Destinations/AddEditDestinationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IBI.Shared.Models.BusTree;
using IBI.Shared.Models.Messages;
using IBI.Web.Infrastructure;
using IBI.Web.Infrastructure.Logger;
using IBI.Shared.Models.Signs;

namespace IBI.Web.ViewModels.Admin.Destinations
{
    public class AddEditSignModel
    {

        public Sign Groups
        {
            get;
            set;
        }

        public int CustomerId { get; set; }

        //public string Name { get; set; }
        public string ParentGroup { get; set; }
        //public string Line {get; set;}

        //public string Text {get; set;}
        //public string Schedule {get; set;}

        //public string SelectionStructure{get; set;}
        //public bool Excluded{get; set;}

        public string PostResult { get; set; }
        public string CancelAction { get; set; } //"back" OR "close"
        public bool LoadAfterSave { get; set; }
        public string ErrorMessage { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string CustomerChanged { get; set; }
         
        public Sign Sign { get; set; }

        //Constructor
        public AddEditSignModel(int customerId, int signId)
        {
            this.CustomerId = customerId;

            this.PostResult = ""; 
            this.Sign = ServiceManager.GetSignItem(signId); 

            if (this.Sign==null)
            {
                this.Sign = new Sign
                {
                    CustomerId = customerId,
                    IsActive = true
                };
            }
        }

        public AddEditSignModel() { }



    }
}

IBI.System/IBI.MVC/ViewModels/Admin/Destinations/AddEditGroupModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IBI.Shared.Models.BusTree;
using IBI.Shared.Models.Messages;
using IBI.Web.Infrastructure;
using IBI.Web.Infrastructure.Logger;
using IBI.Shared.Models.Destinations;

namespace IBI.Web.ViewModels.Admin.Destinations
{
    public class AddEditGroupModel
    {

        public IBI.Shared.Models.Signs.Group Groups
        {
            get;
            set;
        }

        public int CustomerId { get; set; }
        public string ParentGroup { get; set; }
        public int? OldParentId { get; set; }

        public int SortValue { get; set; }

        public string PostResult { get; set; }
        public string CancelAction { get; set; } //"back" OR "close"
        public bool LoadAfterSave { get; set; }
        public string ErrorMessage { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string CustomerChanged { get; set; }

        public IBI.Shared.Models.Signs.Group Group { get; set; }

        //Constructor
        public AddEditGroupModel(int customerId, int groupId)
        {
            this.CustomerId = customerId;

            this.PostResult = "";
            this.Group = ServiceManager.GetSignGroup(groupId);

            if (this.Group == null)
            {
                this.Group = new IBI.Shared.Models.Signs.Group
                {
                    CustomerId = customerId,
                    Excluded = false
                };
            }
            else
            {
                OldParentId = this.Group.ParentGroupId;
            }
            SortValue = this.Group.SortValue;
        }

        public AddEditGroupModel() { }



    }
}

IBI.System/IBI.MVC/ViewModels/Admin/Destinations/ImageAdditionalSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace IBI.Web.ViewModels.Admin.Destinations
{
    [DataContract]
    public class ImageAdditionalSettings
    {
        #region Data
        [DataMember]
        public bool AllCaps { get; set; }
        [DataMember]
        public string LineDivider { get; set; }
        [DataMember]
        public string MainSubDivider { get; set; }
        [DataMember]
        public bool ShowGrid { get; set; }
        #endregion

        #region Label
        [DataMember]
        public string LabelHeading { get; set; }
        [DataMember]
        public string LabelAllCaps { get; set; }
        [DataMember]
        public string LabelLineDivider { get; set; }
        [DataMember]
        public string LabelMainSubDivider { get; set; }
        [DataMember]
        public string LabelShowGrid { get; set; }
        #endregion

        #region Constructors
        public ImageAdditionalSettings(bool pAllCaps=false, string pLineDivider="0", string pMainSubDivider="0", bool pShowGrid=false)
        {
            this.AllCaps = pAllCaps;
            this.LineDivider = pLineDivider;
            this.MainSubDivider = pMainSubDivider;
            this.ShowGrid = pShowGrid;

            this.LabelHeading = "Additional settings";
            this.LabelAllCaps = "All Caps:";
            this.LabelLineDivider = "Line divider:";
            this.LabelMainSubDivider = "Main/Sub divider:";
            this.LabelShowGrid = "Show grid:";
        }
        #endregion

        #region Implementation 
        #endregion
    }
}

IBI.System/IBI.MVC/ViewModels/Admin/Destinations/ImageGeneratorPager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace IBI.Web.ViewModels.Admin.Destinations
{
    [DataContract]
    public class ImageGeneratorPager
    {
        [DataMember]
        public List<string> Img { get; set; }

        [DataMember]
        public int Index { get; set; }

        [DataMember]
        public int Count { get; set; }
    }
}

IBI.System/IBI.MVC/ViewModels/Admin/Destinations/ImageGeneratorTextSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace IBI.Web.ViewModels.Admin.Destinations
{
    [DataContract]
    public class ImageGeneratorTextSettings
    {
        [DataMember]
        private ImageTextSettings LineText { get; set; }
        [DataMember]
        private ImageTextSettings MainText { get; set; }
        [DataMember]
        private ImageTextSettings SubText { get; set; }
        [DataMember]
        private ImageAdditionalSettings Additional { get; set; }
    }
}

IBI.System/IBI.MVC/Controllers/AdminController.cs
using IBI.Shared.Models.Destinations;
using IBI.Shared.Models.ScheduleTreeItems;
using IBI.Shared.Models.SignAddons;
using IBI.Shared.Models.Signs;
using IBI.Shared.Models;
using IBI.Web.Common;
using IBI.Web.Infrastructure;
using IBI.Web.Infrastructure.CustomAttributes;
using IBI.Web.Infrastructure.Logger;
using IBI.Web.ViewModels.Admin.Destinations;
using IBI.Web.ViewModels.Admin.SignAddons;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IBI.Web.Controllers
{
    [AuthorizeLogin]
    public class AdminController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }



        #region Destinations

        [HttpGet]
        public ActionResult Destinations()
        {
            var model = new ViewModels.Admin.Destinations.SignModel(0);
            return View(model);
        }

        [HttpPost]
        public ActionResult Destinations(int? customerId, bool? status)
        {
            var model = new ViewModels.Admin.Destinations.SignModel(customerId??0);
            return View(model);
        }


        [HttpGet]
        public ActionResult GetSignTree(string custAndType)
        {
            //DestinationTree tree = SessionManager.Get<DestinationTree>("DestinationTree");

            string[] arr = custAndType.Split('|');
            int customerId = int.Parse(arr[0]);
            int type = int.Parse(arr[1]);
            bool showInactive = false;
                
            if(arr.Length>2)
            {
                showInactive = arr[2] == "1" ? true : false; 
            }

            if (customerId > 0)
            {
                SignTree tree = ServiceManager.GetSignTree(new SignTree { CustomerID = customerId, UserID = Common.CurrentUser.UserId }, showInactive, true);

                SessionManager.Store("SignTree", tree);

                if (tree != null)
                {

                    if (type==0)
                        return Json(tree.Signs[0].children, JsonRequestBehavior.AllowGet);
                    else
                        return Json(tree.Signs[1].children, JsonRequestBehavior.AllowGet);

                }
            }

            return Json(new List<Sign>(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetSpecialSignTree(int customerId)
        {
            Sign dest = ServiceManager.GetSignGroups(customerId, Common.CurrentUser.UserId);

            return Json(dest.children, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddEditDestination(int customerId, int signId)
        {
            signId = (signId == null || signId <= 0) ? -1 : signId;

            AddEditSignModel model;
                        
            model = new AddEditSignModel(customerId,signId);
           
            return View(model);
        }


        [HttpPost]
        public JsonResult AddEditDestination(AddEditSignModel model)
        {  

            model.Sign.Line = model.Sign.Line ?? "";
            model.Sign.Name = model.Sign.Name ?? "";
            model.Sign.MainText = model.Sign.MainText ?? "";
            model.Sign.SubText = model.Sign.SubText ?? "";


            Sign sign = new Sign();
            if(model.Sign.SignId>0)
            {
                sign = ServiceManager.GetSignItem(model.Sign.SignId);
            }


            sign.CustomerId = model.CustomerId;
            sign.Line= model.Sign.Line;
            sign.MainText = model.Sign.MainText;
            sign.SubText = model.Sign.SubText;
            sign.Name = model.Sign.Name;
            sign.IsActive = model.Sign.IsActive;
            sign.GroupId = model.Sign.GroupId;
            sign.ParentGroupId = model.Sign.ParentGroupId ?? null;
            sign.IsActive = model.Sign.IsActive;
            sign.IsGroup = model.Sign.IsGroup;
            sign.Priority = model.Sign.Priority;
            
            sign.ScheduleId = model.Sign.ScheduleId ?? null;
            
            sign.SetNode();

            
            model.LoadAfterSave = true;

            //checks
            if (String.IsNullOrEmpty(sign.Name)) 
            {
                model.PostResult =  "false";
                model.ErrorMessage = "Sign name cannot be empty";
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            if (String.IsNullOrEmpty(sign.MainText))
            {
                model.PostResult = "false";
                model.ErrorMessage = "Main Text cannot be empty";
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            if (sign.ParentGroupId == null)
            {
                model.PostResult = "false";
                model.ErrorMessage = "You must select a parent group node";
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            if (sign.ParentGroupId == 10000001) // trying to add SignItem at Special Tree's Root
            {
                sign.ParentGroupId = null;
            }

            if(sign.ParentGroupId == 10000002) // trying to add SignItem at Line Items Tree's Root
            {
                model.PostResult = "false";
                model.ErrorMessage = "You cannot put signs at the root level of 'Line selection buttons', please select a sub group";
                return Json(model, JsonRequestBehavior.AllowGet);
            }

             
            Sign existingSign = ServiceManager.FindSignItem(sign.CustomerId, sign.ParentGroupId, sign.Line, sign.Name, sign.MainText, sign.SubText);

                bool existScheduleId = ServiceManager.FindScheduleId(sign.ScheduleId??0);

            if (sign.ScheduleId!=null && sign.ScheduleId!=0 && !existScheduleId)
            {
                model.PostResult = "false";
                model.ErrorMessage = "Failed to save. Invalid Schedule Id";
            
            } 
            else if (existingSign != null && existingSign.SignId!=sign.SignId)
            {
                //already similar destination exist at that level
                model.PostResult = "false";
                model.ErrorMessage = "Failed to save. Destination already exists at that level";
                //ModelState.AddModelError("AlreadyExists", "Destination Already exists at this level");
                
            }
            else 
            { 
            
                bool result = ServiceManager.SaveSign(sign);

                model.Sign = sign;

                model.PostResult = result ? "true" : "false";
                //ModelState.AddModelError("AlreadyExists", "Destination Already exists at this level");
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult DeleteSign(int signId) {
             
            return Json(ServiceManager.DeleteSign(signId), JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult DestinationImages(string id)
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddEditGroup(int customerId, int groupId)
        {
            groupId = (groupId == null || groupId <= 0) ? -1 : groupId;
            AddEditGroupModel model;            
            model = new AddEditGroupModel(customerId, groupId);
             
            return View(model);
        }


        [HttpPost]
        public JsonResult AddEditGroup(AddEditGroupModel model)
        {

            model.Group.GroupName = model.Group.GroupName ?? "";


            Group group = new Group();
            if (model.Group.GroupId > 0)
            {
                group = ServiceManager.GetSignGroup(model.Group.GroupId);
            }


            group.CustomerId = model.CustomerId;
            group.GroupName = model.Group.GroupName;
            group.Excluded  = model.Group.Excluded;
            group.ParentGroupId = model.Group.ParentGroupId ?? null;
            group.SortValue  = model.SortValue;

            model.LoadAfterSave = true;

            //checks
            if (String.IsNullOrEmpty(group.GroupName))
            {
                model.PostResult = "false";
                model.ErrorMessage = "Group name cannot be empty";
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            if (group.ParentGroupId==null)
            {
                model.PostResult = "false";
                model.ErrorMessage = "You must select a parent group node";
                return Json(model, JsonRequestBehavior.AllowGet);
            }

            if (group.ParentGroupId == 10000001)
            {
                group.ParentGroupId = null;
                group.GroupName = group.GroupName.Replace("#", "");
            }

            if (group.ParentGroupId == 10000002)
            {
                group.ParentGroupId = null;
                group.GroupName = "#" + group.GroupName.Replace("#", "");
            }
             
            Group existingSignGroup = ServiceManager.FindSignGroup(group.CustomerId, group.ParentGroupId, group.GroupName);


            if (group.GroupId == group.ParentGroupId || (existingSignGroup != null && existingSignGroup.GroupId != group.GroupId))
            {
                //already similar destination exist at that level
                model.PostResult = "false";
                model.ErrorMessage = "Failed to save. Group already exists at that level";
                //ModelState.AddModelError("AlreadyExists", "Destination Already exists at this level");

            }
            else
            {

                bool result = ServiceManager.SaveSignGroup(group,model.OldParentId);

                model.Group = group;

                model.PostResult = result ? "true" : "false";
                //ModelState.AddModelError("AlreadyExists", "Destination Already exists at this level");
            }

IBI.System/IBI.MVC/Views/Admin/AddEditSignAddon.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

@model IBI.Web.ViewModels.Admin.SignAddons.AddEditSignAddonModel

@using Kendo.Mvc.UI
@using IBI.Web.Common

@{
    ViewBag.Title = "Add Sign Addon";
    Layout = null;
}


<style type="text/css">

div.options {
        left: -20px;
        position: relative;
    }
div.options > label > input {
    visibility: hidden;
    display: inline-block;

}

div.options > label {
    display: inline-block;
    height: 27px;
    width: 70px;
    text-align: left;
}

div.options > label > img {
    display: inline-block;
    padding: 0px;
    height:30px;
    width:30px;
    background: white;
    border-radius: 6px;
    position: relative;
    top: -5px;
}

div.options > label > input:checked +img {  
    background-image: url(../images/destinations/inactive.png);
    background-repeat: no-repeat;
    background-position:center center;
    background-color: white;
}
</style>
<!--start - Script for BusTree-->
<script type="text/javascript">

        $(document).ready(function () {

            //$(".dynatree-icon").css('backgroundImage', 'url(../content/dynatree/skin/scrollright_grey.png)');

        });
      
</script>
<!--end - Script for BusTree-->

<script>

    function FormSuccess(data) {

        //alert(result.PostResult + '-' + result.ErrorMessage);
        var result = data.PostResult;
        var errMsg = data.ErrorMessage;


        if (result == 'true') {
            jAlert("Sign Addon saved successfully", "Success");
            bReloadTree = true;
            $('#AddEditSignAddon').data("kendoWindow").close();
        }
        else {
            jAlert(errMsg, "Failure");
        }

        $('input[type=submit]').removeAttr("disabled").removeClass("disabled");
    }



    $(document).ready(function () {
        $('#closePopup').click(function () {
            bReloadTree = true;
            $('#AddEditSignAddon').data("kendoWindow").close();
        })
    });


    $(document).ready(function () {

        var openedForEdit = '@(Model.SignAddon.SignAddonItemId)';
        //alert('@(Model.SignAddon.SignAddonItemId)');
        if (openedForEdit == '0') {
            $('#deleteRecord').attr("disabled", true).addClass("disabled");
            $('#deleteRecord').css('display', 'none');
        }


        //$("input:checkbox").click(function () {
        //    var group = "input:checkbox[name='" + $(this).attr("name") + "']";
        //    $(group).attr("checked", false);
        //    $(this).attr("checked", true);
        //});


        $(".radio").click(function () {
            var group = "input:checkbox[name='" + $(this).attr("name") + "']";
            $(group).attr("checked", false);
            $(this).attr("checked", true);
        });

        $('#deleteRecord').click(function () {
            //alert('deleting');
            jConfirm('Are you sure to delete this  Addon?', 'Confirmation', function (r) {
                if (r == true) {

                    $('#deleteRecord').attr("disabled", true).addClass("disabled");
                    $('#deleteRecord').css('display', 'none');

                    $.get("../Admin/DeleteSignAddon", { signAddonItemId: "@Model.SignAddon.SignAddonItemId" })
                         .done(function () {
                             jAlert("Addon deleted successfully", "Deleted");

                             bReloadTree = true;
                             $('#AddEditSignAddon').data("kendoWindow").close();
                         })
                         .fail(function () {
                             jAlert("Sign addon cannot be deleted", "Failure");
                         });

                    $('#deleteRecord').removeAttr("disabled").removeClass("disabled");

                }
            });


        })
    });
    function CloseWindow() {
        window.$("#AddEditSignAddon").data("kendoWindow").close();
    }
</script>



<!--jAlert-->
<script src="@Url.Content("~/Scripts/plugins/jAlert/jquery.alert.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Scripts/plugins/jAlert/jquery.alert.css")" rel="stylesheet" type="text/css" />

<div id="AjaxContents" class="input-table">

    <div>
        @{
       var htmlAttributes = new Dictionary<string, object> { { "data-autopostback", "true" } }; 
        }
        @using (Ajax.BeginForm("AddEditSignAddon", "Admin", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, OnSuccess = "FormSuccess", OnBegin = "beginAjaxSubmit" }))
         {
             
            @Html.ValidationSummary(true, "Message couldn't be saved. Please correct the errors and try again.")
                        
            <table style="width: 100%; height: 100%; margin: 0 auto;position: relative;right: -8px;">
                <tr >
                    <td colspan="2" style="text-align: left;" class="label"> @(Model.SignAddon.SignAddonItemId == 0 ? Html.Raw("Add") : Html.Raw("Edit")) Sign Addon</td>
                    <td style="text-align: right">
                        <img src="~/Images/infotainment/close.png" onclick="CloseWindow()" />
                    </td>
                </tr>
                @*<tr>
         <td class="label" colspan="3" style="text-align: left">Group
         </td>
     </tr>
    <tr>
         <td colspan="2">
             <div style="border: solid 1px #aaa; border-radius: 3px; padding: 5px;;width:394px;">
                 <div id="destinationTree" style="width: 394px; height: 200px; overflow-y: scroll; overflow-x: hidden;" />
             </div>
         </td>
         <td></td>
     </tr>*@
                <tr class="tr">
                    <td class="title">
                        <label>Name</label>
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.SignAddon.Name, new { @class = "inputbox", placeholder = "Input Name" })
                    </td>
                    <td>
                        @Html.ValidationMessageFor(model => model.SignAddon.Name)
                    </td>
                </tr>

               

                <tr class="tr">
                    <td class="title">                       
                        @Html.Label("Sign Text")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.SignAddon.SignText, new { @class="inputbox" , placeholder="Input Sign Text" })
                    </td>
                    <td>
                        @Html.ValidationMessageFor(model => model.SignAddon.SignText)
                    </td>
                </tr>
                @*<tr class="tr">
                    <td class="title">
                        @Html.Label("UDP Text")
                    </td>
                    <td>
                        @Html.TextBoxFor(model => model.SignAddon.UdpText, new { @class="inputbox" , placeholder="Input UDP Text" })
                    </td>
                    <td>
                        @Html.ValidationMessageFor(model => model.SignAddon.UdpText)
                    </td>
                </tr>*@

                  
                <tr class="tr">
                    <td class="title">
                        <label>Active</label>
                    </td>
                    <td>
                       @*

                        @Html.RadioButtonFor(model => model.Sign.IsActive, "true", new { id = "yes" })
                        @Html.Label("yes", "Yes")

                        @Html.RadioButtonFor(model => model.Sign.IsActive, "false", new { id = "no" })
                        @Html.Label("no", "No")

                       *@
                                               
                        @*<div class="options">
                            <label title="Yes" style="position: relative; width: 71px;left:-3px">
                                <input type="radio" name="Sign.IsActive" value="true" @(Model.Sign.IsActive?"checked":"") /> 
                              Yes
                                <img />
                            </label>
                            <label title="No" style=" position: relative; left: -25px; ">
                                <input type="radio" name="Sign.IsActive" value="false" @(!Model.Sign.IsActive?"checked":"") />
                                No
                                <img />
                            </label>   
                        </div>*@

                       @* <div class="options">
                            <label title="Yes" style="position: relative; width: 71px;left:-3px">
                                <input type="radio" name="Sign.IsActive" value="true" @(Model.Sign.IsActive?"checked":"") /> 
                                <label for="male" style="position: relative;top: -9px;" >Yes</label>
                                <img />
                            </label>
                            <label title="No" style=" position: relative; left: -25px; ">
                                <input type="radio" name="Sign.IsActive" value="false" @(!Model.Sign.IsActive?"checked":"") />
                                <label for="male" style="position: relative;top: -9px;" >No</label>
                                <img />
                            </label>   
                        </div>*@

                        <label for="yes">Yes</label>
                        <input type="checkbox" class="radio" value="true" name="SignAddon.IsActive" @(Model.SignAddon.IsActive?"checked":"") style="width: 2em;height: 2em;" />
                        <label for="no">No</label> 
                        <input type="checkbox" class="radio" value="false" name="SignAddon.IsActive" @(!Model.SignAddon.IsActive?"checked":"")  style="width: 2em;height: 2em;" />



                    </td>

                </tr>

                <tr>
                    <td style="display: hidden;">
                        <!--hidden fields [the fields which we dont want to edit ]-->
                        @Html.HiddenFor(model => model.SignAddon.SignAddonItemId )
                        @Html.HiddenFor(model => model.SignAddon.GroupId )
                        @Html.HiddenFor(model => model.SignAddon.ParentGroupId)
                        @Html.HiddenFor(model => model.SignAddon.Priority)
                        @Html.HiddenFor(model => model.CustomerId)

                    </td>
                    <td>
                        @*<a href="#" class="delete"  id="deleteRecord">Delete</a>
                        <a href="#" class="cancel"  id="closePopup">Cancel</a> 
                        <a href="#" class="cancel"  id="closePopup" onclick="document.forms[0].submit()">New SAVE</a> *@
                        @* <div style="display: inline-block">
                            <input class="buttonStyle" type="submit" value="Save" onclick="" /> 
                        </div>*@

                        <div>
                            <div style="display: inline-block; padding-right: 10px">
                                <a href="#" id="deleteRecord" style="text-decoration: none">
                                    <div class="deletebutton">Delete</div>
                                </a>
                            </div>
                            <div style="display: inline-block; padding-right: 10px">
                                <a href="#" id="closePopup" style="text-decoration: none">
                                    <div class="cancelbutton">Cancel</div>
                                </a>
                            </div>
                            <div style="display: inline-block; position: relative; top: -16px;">
                                <input class="savebutton" type="submit" value="Save" />
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
              
            }

        <script>
                
        </script>

    </div>
    <!--inputTable - end-->

</div>
<!--AjaxContents - end-->

IBI.System/IBI.MVC/Views/Admin/DestinationImages.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DestinationImages</title>
</head>
<body>
    <div>
        DestinationImages
   
    </div>
</body>
</html>